version: '3.8'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: pack_weightr_db
    ports:
      - "5432:5432"
    env_file: ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file: ./.env
    restart: unless-stopped

volumes:
  postgres-data: